name: FRC Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wpilib==2019.2.3
        pip install pyfrc==2019.1.0
        pip install pynetworktables==2019.0.2
    - name: Build
      run: |
        python robot.py add-tests
        python robot.py test
    - name: Slack notification
      env:
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
        SLACK_USERNAME: Github Status # Optional. (defaults to webhook app)
        SLACK_CHANNEL: programming # Optional. (defaults to webhook)
        SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
      uses: Ilshidur/action-slack@master
      with:
        args: 'A new commit has been pushed.' # Optional
