name: FRC Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wpilib==2019.2.3
        pip install pyfrc==2019.1.0
        pip install pynetworktables==2019.0.2
    - name: Build
      run: |
        python robot/robot.py add-tests
        python robot/robot.py test
